/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 Heart.gltf 
Author: Azamuki (https://sketchfab.com/Azamuki)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/heart-in-love-f39ce19b92e246268f4c501b72ea7d0e
Title: Heart in Love
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Heart(props) {
  const { nodes, materials } = useGLTF("/Heart.gltf");
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Heart_Heart_0.geometry}
        material={materials.Heart}
        rotation={[-Math.PI / 2, Math.PI / 2, 0]}
        scale={100}
      />
      <mesh
        geometry={nodes.Marble_Marble_0.geometry}
        material={materials.Marble}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      />
    </group>
  );
}

useGLTF.preload("/Heart.gltf");
